# Build and deploy workflow

name: Build and Deploy
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab
permissions:
  contents: write


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains one job with two main steps: build and deploy
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        env: # Set Secret Key
          secret_adobe_api_key: ${{ secrets.ADOBE_API_KEY }}

      # I believe the site is pre-built, otherwise an install/build step goes here

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        # https://github.com/JamesIves/github-pages-deploy-action
        with:
          folder: . # build # The folder the action should deploy.
                    # A . signifies the root of the directory
