name: Build and Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          secret_adobe_api_key: ${{ secrets.ADOBE_API_KEY }}
        
      # - name: check if can even access key
      #   run: echo ${{ secrets.TEST_SECRET }}

      - name: Replace API Key
        run: |
          sed -i "s/REPLACE_WITH_YOUR_API_KEY/$(echo "${{ secrets.ADOBE_API_KEY }}" | sed 's/\//\\\//g')/g" index.html

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3
          python3 -m pip install --upgrade pip
      # python3 -m pip install requests beautifulsoup4

      # - name: Debug Workflow Environment
      #   run: |
      #     echo "Current directory: $(pwd)"
      #     echo "Contents of current directory:"
      #     ls -al

      - name: Get PDF URL
        id: get_pdf_url
        run: |
          pdf_url_value=$(python get_pdf_url.py)
          echo "PDF_URL=${pdf_url_value}" >> $GITHUB_ENV

      - name: Replace PDF file
        run: |
          sed -i "s/REPLACE_WITH_PDF_URL/$(echo "${{ env.PDF_URL }}" | sed 's/\//\\\//g')/g" index.html
      
      - name: Print Output for Debugging
        run: cat index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

  deploy:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
